version: '3'

services:
  app-db:
    image: postgres:14
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./services/app-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  data-generator:
    build:
      context: ./services/data-generator
    restart: on-failure
    environment:
      - POSTGRES_HOST=app-db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      app-db:
        condition: service_healthy
