FROM confluentinc/cp-kafka-connect:7.1.1

WORKDIR /usr/share/java

RUN curl -O https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.9.0.Final/debezium-connector-postgres-1.9.0.Final-plugin.tar.gz
RUN tar xzf debezium-connector-postgres-1.9.0.Final-plugin.tar.gz
